services:

  db:
    build: .
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: wp_database
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wp:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - ./wordpress:/var/www/html

volumes:
  mariadb_data:
